trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    sudo apt-get update
    sudo apt-get install -y ninja-build
  displayName: 'Install Dependencies'
  
- task: Build@1
  displayName: 'Project and Build configuration'
  inputs:
    cmakeArgs: '-B build -G "Ninja" -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc

- task: Build@1
  displayName: 'Build binaries'
  inputs:
    cmakeArgs: '--build build'

- task: Staging@2
  displayName: 'Stage binaries'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/build'
    Contents: |
      ingest
      report
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishPipelineArtifact@1
  displayName: 'Publish Build Artifacts'
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifact: 'cpp-binaries-$(Build.BuildId)'
    publishLocation: 'pipeline'